service: bash-runtime

frameworkVersion: ">=1.34.0 <2.0.0"

provider:
  name: aws
  runtime: provided
  stage: dev
  region: eu-central-1
  memorySize: 128
  logRetentionInDays: 7
  versionFunctions: false
  deploymentBucket: dasniko.serverless.deployments.${self:provider.region}
  tracing: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - xray:PutTraceSegments
        - xray:PutTelemetryRecords
      Resource: "*"

plugins:
  - serverless-plugin-tracing

package:
  exclude:
    - package.json
    - node_modules

functions:
  bash:
    handler: function.handler
    layers:
      - Ref: BashLambdaLayer

layers:
  bash:
    path: layer
